version: "3"

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.create_ssl
      args:
        APP_URL: ${APP_URL}
    ports:
      - "80:80"
    volumes:
      - ./site:/usr/share/nginx/html
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
