FROM nginx:1.20.2-alpine

COPY ./default-prod-ssl.conf /etc/nginx/conf.d/default.conf
COPY ./gzip.conf /etc/nginx/conf.d/gzip.conf

RUN mkdir -p /var/www/app/site/static && \
    chmod 755 /var/www/app/site/static

ARG APP_URL
RUN sed -i "s|\$APP_URL|$APP_URL|g" /etc/nginx/conf.d/default.conf